### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by buschtoens**
This is a little refactor of the test cases.

Instead of having all helpers rendered in the application template, every case gets its own route. This also fixes the problem mentioned in #5.

This is a necessary merge for the third case mentioned in #8.

### CODE REVIEW

**Comment by buschtoens** [comment]
Please merge #5 and #7 first, so I can rebase this and refactor those tests aswell.

**Comment by rlivsey** [comment]
Hi @buschtoens, thanks for all the awesome work on this - I've added you as a collaborator so merge away!

**Comment by buschtoens** [comment]
Sweet! Thank you :)

**Comment by buschtoens** [comment]
Just rebased and focre-pushed to keep the history clean. I'll run the tests locally and merge.

**Pull request merged**
