### PR TITLE
Update ember-cli ~3.1.4

### LINKED ISSUE #49: Deprecation Warning when updating to ember 2.18.2
Getting the following deprectation warning when doing an ember s after updating to ember-cli@2.18.2

An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker

### PR DESCRIPTION
**Pull request by lozjackson**
fixes #49

### CODE REVIEW

**Comment by lozjackson** [comment]
@rlivsey Can this PR be merged?

...And what is the status of this repo, is it being actively maintained?

**Comment by apellerano-pw** [comment]
Thanks for doing this, I am also looking forward to these changes making their way into a new release

**Comment by jcaffey** [comment]
+1 please merge!

**Comment by erichuang310** [comment]
👍 LGTM!

**Pull request merged**
