### PR TITLE
Fix htmlSafe import

### LINKED ISSUE #105: htmlSafe import is causing error in production build
I'm getting the following error in our app when building for production since upgrading to ember 3.27

> Uncaught (in promise) TypeError: (0 , t.htmlSafe) is not a function

This line https://github.com/minutebase/ember-inline-svg/blob/master/addon/helpers/inline-svg.js#L1 should be changed to import from `@ember/template` instead of `@ember/string`

### PR DESCRIPTION
**Pull request by lozjackson**
Fixes #105 

@rlivsey

### CODE REVIEW

**Comment by lozjackson** [comment]
@rlivsey bump - can we merge this?

**Comment by bitwolfe** [comment]
@raido Are you able to get this merged and released?

**Comment by raido** [comment]
I'll try to get it released next week. :)

**Comment by raido** [comment]
Duplicate of https://github.com/minutebase/ember-inline-svg/pull/95.

**Pull request closed without merging**
